// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: pkg/fixture/bar.proto

package fixture

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// global enum
type BAR int32

const (
	BAR_BAR_UNSPECIFIED BAR = 0
	BAR_BAR_TYPE_1      BAR = 1
	BAR_BAR_TYPE_2      BAR = 2
)

// Enum value maps for BAR.
var (
	BAR_name = map[int32]string{
		0: "BAR_UNSPECIFIED",
		1: "BAR_TYPE_1",
		2: "BAR_TYPE_2",
	}
	BAR_value = map[string]int32{
		"BAR_UNSPECIFIED": 0,
		"BAR_TYPE_1":      1,
		"BAR_TYPE_2":      2,
	}
)

func (x BAR) Enum() *BAR {
	p := new(BAR)
	*p = x
	return p
}

func (x BAR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BAR) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_fixture_bar_proto_enumTypes[0].Descriptor()
}

func (BAR) Type() protoreflect.EnumType {
	return &file_pkg_fixture_bar_proto_enumTypes[0]
}

func (x BAR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BAR.Descriptor instead.
func (BAR) EnumDescriptor() ([]byte, []int) {
	return file_pkg_fixture_bar_proto_rawDescGZIP(), []int{0}
}

type FOO_BAR int32

const (
	FOO_BAR_UNSPECIFIED FOO_BAR = 0
	FOO_BAR_TYPE_1      FOO_BAR = 1
	FOO_BAR_TYPE_2      FOO_BAR = 2
)

// Enum value maps for FOO_BAR.
var (
	FOO_BAR_name = map[int32]string{
		0: "BAR_UNSPECIFIED",
		1: "BAR_TYPE_1",
		2: "BAR_TYPE_2",
	}
	FOO_BAR_value = map[string]int32{
		"BAR_UNSPECIFIED": 0,
		"BAR_TYPE_1":      1,
		"BAR_TYPE_2":      2,
	}
)

func (x FOO_BAR) Enum() *FOO_BAR {
	p := new(FOO_BAR)
	*p = x
	return p
}

func (x FOO_BAR) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FOO_BAR) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_fixture_bar_proto_enumTypes[1].Descriptor()
}

func (FOO_BAR) Type() protoreflect.EnumType {
	return &file_pkg_fixture_bar_proto_enumTypes[1]
}

func (x FOO_BAR) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FOO_BAR.Descriptor instead.
func (FOO_BAR) EnumDescriptor() ([]byte, []int) {
	return file_pkg_fixture_bar_proto_rawDescGZIP(), []int{0, 0}
}

// nested enum
type FOO struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bar FOO_BAR `protobuf:"varint,1,opt,name=bar,proto3,enum=fixture.FOO_BAR" json:"bar,omitempty"`
}

func (x *FOO) Reset() {
	*x = FOO{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_fixture_bar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FOO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FOO) ProtoMessage() {}

func (x *FOO) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_fixture_bar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FOO.ProtoReflect.Descriptor instead.
func (*FOO) Descriptor() ([]byte, []int) {
	return file_pkg_fixture_bar_proto_rawDescGZIP(), []int{0}
}

func (x *FOO) GetBar() FOO_BAR {
	if x != nil {
		return x.Bar
	}
	return FOO_BAR_UNSPECIFIED
}

var File_pkg_fixture_bar_proto protoreflect.FileDescriptor

var file_pkg_fixture_bar_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x6b, 0x67, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x62, 0x61,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65,
	0x22, 0x65, 0x0a, 0x03, 0x46, 0x4f, 0x4f, 0x12, 0x22, 0x0a, 0x03, 0x62, 0x61, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x2e, 0x46,
	0x4f, 0x4f, 0x2e, 0x42, 0x41, 0x52, 0x52, 0x03, 0x62, 0x61, 0x72, 0x22, 0x3a, 0x0a, 0x03, 0x42,
	0x41, 0x52, 0x12, 0x13, 0x0a, 0x0f, 0x42, 0x41, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43,
	0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x41, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x31, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x41, 0x52, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x32, 0x10, 0x02, 0x2a, 0x3a, 0x0a, 0x03, 0x42, 0x41, 0x52, 0x12, 0x13,
	0x0a, 0x0f, 0x42, 0x41, 0x52, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x41, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x31, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x42, 0x41, 0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x32, 0x10, 0x02, 0x42, 0x5f, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x2e, 0x66, 0x69, 0x78, 0x74, 0x75,
	0x72, 0x65, 0x42, 0x08, 0x42, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x0a,
	0x2e, 0x2e, 0x2f, 0x66, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0xa2, 0x02, 0x03, 0x46, 0x58, 0x58,
	0xaa, 0x02, 0x07, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0xca, 0x02, 0x07, 0x46, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0xe2, 0x02, 0x13, 0x46, 0x69, 0x78, 0x74, 0x75, 0x72, 0x65, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x46, 0x69, 0x78,
	0x74, 0x75, 0x72, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_fixture_bar_proto_rawDescOnce sync.Once
	file_pkg_fixture_bar_proto_rawDescData = file_pkg_fixture_bar_proto_rawDesc
)

func file_pkg_fixture_bar_proto_rawDescGZIP() []byte {
	file_pkg_fixture_bar_proto_rawDescOnce.Do(func() {
		file_pkg_fixture_bar_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_fixture_bar_proto_rawDescData)
	})
	return file_pkg_fixture_bar_proto_rawDescData
}

var file_pkg_fixture_bar_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pkg_fixture_bar_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pkg_fixture_bar_proto_goTypes = []interface{}{
	(BAR)(0),     // 0: fixture.BAR
	(FOO_BAR)(0), // 1: fixture.FOO.BAR
	(*FOO)(nil),  // 2: fixture.FOO
}
var file_pkg_fixture_bar_proto_depIdxs = []int32{
	1, // 0: fixture.FOO.bar:type_name -> fixture.FOO.BAR
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_fixture_bar_proto_init() }
func file_pkg_fixture_bar_proto_init() {
	if File_pkg_fixture_bar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_fixture_bar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FOO); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_fixture_bar_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_fixture_bar_proto_goTypes,
		DependencyIndexes: file_pkg_fixture_bar_proto_depIdxs,
		EnumInfos:         file_pkg_fixture_bar_proto_enumTypes,
		MessageInfos:      file_pkg_fixture_bar_proto_msgTypes,
	}.Build()
	File_pkg_fixture_bar_proto = out.File
	file_pkg_fixture_bar_proto_rawDesc = nil
	file_pkg_fixture_bar_proto_goTypes = nil
	file_pkg_fixture_bar_proto_depIdxs = nil
}
